### ISSUE TITLE
Test NavX Gyro 

### ISSUE THREAD

**Issue by ashwinc12** [FRCteam4909/2019-Deep-Space#74] opened 2019-02-08 20:53 UTC
-Use gyro to align with stilts

**Comment by roshanr10** [comment] 2019-02-08 21:50
Potential duplicate of #63? Also, the NavX is not guaranteed to work in it's current orientation, just something to think about. That said, I think it's a standard PATA/IDE connection you'll find standard in any desktop pre-2006, so we might be able to salvage a ribbon cable to mount it elsewhere. Or, we could test the USB connection– just something to think about

**Closed** 2019-02-09 03:18 UTC
